# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 415948956384cf455c3ee99c8d727da5a302d93be01980e55abece4e3036e8d4bdd41416ffe0124955674c67c48b99401bd798b9277f01834ed1fe8410a729b2

test:
  secret_key_base: b858e29ed024e74f26e55d24ee7ed66a13e3dfb614f26d5d508cacde0756a3a8b6b159c4bd755bcaf1038acce2c64f9d0f4b6040c2377c5674fb3a8005239dad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
